### PR TITLE
Frontend: slight UI change in EventPage

### PR DESCRIPTION
**Pull request by kubaflo**
Changed Race and Rate to be in the same row (Race on the left
side, Rate on the right side) instead of being one on top of
each other.

Fixes https://gitlab.com/nodeffect/backlog/-/issues/27

### CODE REVIEW

**Comment by knocte** [comment]
You're forgetting the "Fixes" sentence in commit msg.

**Comment by knocte** [comment]
When you update a commit msg, you have to update PR title and PR description to match the commit mesage.

**Comment by siwatanejo** [comment]
> When you update a commit msg, you have to update PR title and PR description to match the commit message.

Hello?

**Comment by siwatanejo** [comment]
> You're forgetting the "Fixes" sentence in commit msg.

And you're forgetting **again** the "Fixes" sentence in the 2nd commit msg.

**Pull request merged**
